import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { afterAll, beforeAll, describe, expect, it } from 'vitest'

import {
  GRAPH_ARTIFACT_V2_HEADER,
  loadGraphArtifact,
  serializeGraphArtifactV2,
  type LoadedGraphArtifact,
} from '../../src/contracts/graph-artifact.js'
import { NORMALIZED_ACCOUNTING_ARTIFACT_KEY } from '../../src/contracts/graph-artifact-payload.js'
import { generateGraph } from '../../src/infrastructure/generate.js'
import { pinnedSourceModule, type PinnedSourceModule } from './helpers/pinned-source-module.js'

/**
 * The load-bearing Stage 3 gate: real bytes, real readers.
 *
 * Every artifact under test here is produced by a real writer running over a
 * real generated corpus, never hand-assembled. A hand-built object proves that
 * a validator accepts a shape; it says nothing about whether a reader that
 * predates the feature can still read a file this version writes.
 */

/** The commit #658 branched from -- the last reader that knows nothing of it. */
const PRE_658_COMMIT = '31ad2168c442891096911871116072934e7ae0a6'
const PRE_658_DIGEST = '6be2c66195a652dd2ad2517766acd2b5676402e6673d6fe60f7871cfffe423fa'

/** The approved Stage 2 head -- the last writer that emitted no accounting. */
const PRE_STAGE3_COMMIT = '580f59f6e423a257807593d162849cba11676346'
const PRE_STAGE3_DIGEST = 'a6d1017db7c0ccd07a98f09dd9ba28bdf3b2d143a90fa2c802ae8af7ab089e20'

interface HistoricalLoader {
  readonly loadGraphArtifact: (bytes: Uint8Array | string) => {
    readonly format: string
    readonly graph: Record<string, unknown> & {
      numberOfFacts: () => number
      numberOfOccurrences: () => number
      numberOfEndpointPairs: () => number
    }
    readonly receipt: Record<string, unknown> & {
      accounting_scope: string
      status: string
      endpoint_identity: { fact_pair_counts: unknown; reason_fact_counts: unknown }
    }
  }
}

interface HistoricalWriter {
  readonly serializeGraphArtifactV2: (input: Record<string, unknown>) => Buffer
}

interface HistoricalBuild {
  readonly buildFromJson: (extraction: unknown, options: Record<string, unknown>) => unknown
}

/** A small but genuine TypeScript workspace, extracted by the real pipeline. */
function workspace(): string {
  const root = mkdtempSync(join(tmpdir(), 'madar-compat-'))
  mkdirSync(join(root, 'src'), { recursive: true })
  writeFileSync(
    join(root, 'src', 'service.ts'),
    'export class Service {\n  run(): void { helper() }\n}\nexport function helper(): void {}\n',
  )
  writeFileSync(
    join(root, 'src', 'caller.ts'),
    "import { Service } from './service.js'\nexport function main(): void { new Service().run() }\n",
  )
  writeFileSync(
    join(root, 'src', 'store.ts'),
    "import { helper } from './service.js'\nexport function save(): void { helper() }\n",
  )
  return root
}

/** Reframes decoded bytes so a controlled edit stays a real artifact file. */
function reframe(bytes: Buffer, edit: (payload: Record<string, unknown>) => void): Buffer {
  const payload = JSON.parse(bytes.toString('utf8').slice(GRAPH_ARTIFACT_V2_HEADER.length)) as Record<string, unknown>
  edit(payload)
  return Buffer.from(`${GRAPH_ARTIFACT_V2_HEADER}${JSON.stringify(payload)}\n`, 'utf8')
}

let currentBytes: Buffer
let currentLoad: LoadedGraphArtifact
let preStage3Bytes: Buffer
let pre658: PinnedSourceModule
let preStage3: PinnedSourceModule
let historicalLoader: HistoricalLoader

beforeAll(async () => {
  // Actual generated bytes: the real extractor, the real build, the real
  // publication path, read back off disk exactly as they were written.
  const root = workspace()
  generateGraph(root, { noHtml: true })
  currentBytes = readFileSync(join(root, 'out', 'graph.madar'))
  currentLoad = loadGraphArtifact(currentBytes)

  pre658 = pinnedSourceModule({
    commit: PRE_658_COMMIT,
    entries: ['src/contracts/graph-artifact.ts'],
    digest: PRE_658_DIGEST,
  })
  historicalLoader = await pre658.load<HistoricalLoader>('src/contracts/graph-artifact.ts')

  // Real pre-Stage-3 bytes, produced by the writer that stood at the approved
  // Stage 2 head rather than by asking today's writer to pretend.
  preStage3 = pinnedSourceModule({
    commit: PRE_STAGE3_COMMIT,
    entries: ['src/contracts/graph-artifact.ts', 'src/pipeline/build.ts'],
    digest: PRE_STAGE3_DIGEST,
  })
  const oldWriter = await preStage3.load<HistoricalWriter>('src/contracts/graph-artifact.ts')
  const oldBuild = await preStage3.load<HistoricalBuild>('src/pipeline/build.ts')
  const oldGraph = oldBuild.buildFromJson(extractionOf(root), {
    directed: true,
    accounting: 'normalized_extraction_boundary',
  })
  preStage3Bytes = oldWriter.serializeGraphArtifactV2({
    graph: oldGraph,
    repositoryRevision: 'compat-fixture',
    generationMode: 'full',
    generatedAt: '2026-08-24T00:00:00.000Z',
  })
}, 120_000)

afterAll(() => {
  pre658?.dispose()
  preStage3?.dispose()
})

/** The extraction the generated artifact records, replayed for the old build. */
function extractionOf(root: string): Record<string, unknown> {
  const loaded = loadGraphArtifact(readFileSync(join(root, 'out', 'graph.madar')))
  return {
    schema_version: 1,
    directed: loaded.graph.isDirected(),
    nodes: loaded.graph.nodeIds().map((id) => ({ id, label: id, file_type: 'code' })),
    edges: loaded.graph.factRecords().map(({ fact }) => ({
      source: fact.source,
      target: fact.target,
      relation: fact.relation,
      confidence: 'EXTRACTED',
    })),
  }
}

describe('S3-5 — the pinned historical source is the source it claims to be', () => {
  it('pins the pre-#658 loader by commit and closure digest', () => {
    expect(pre658.commit).toBe(PRE_658_COMMIT)
    expect(pre658.digest).toBe(PRE_658_DIGEST)
    expect(pre658.files).toContain('src/contracts/graph-artifact.ts')
    expect(pre658.files).toContain('src/contracts/graph.ts')
  })

  it('pins the pre-Stage-3 writer by commit and closure digest', () => {
    expect(preStage3.commit).toBe(PRE_STAGE3_COMMIT)
    expect(preStage3.digest).toBe(PRE_STAGE3_DIGEST)
  })

  it('really is the older reader, not this one under another name', () => {
    // The decisive non-vacuity check. #658 added the normalized snapshot to
    // KnowledgeGraph; a graph produced by the pinned loader must not have it,
    // or the control silently routed through today's implementation.
    const loaded = historicalLoader.loadGraphArtifact(currentBytes)
    expect(typeof (loaded.graph as { normalizedIntegritySnapshot?: unknown }).normalizedIntegritySnapshot)
      .toBe('undefined')
    expect(typeof loaded.graph.numberOfFacts).toBe('function')
  })
})

describe('S3-5 — the artifact under test is real generated output', () => {
  it('was written by the publication path, not assembled by a test', () => {
    expect(currentBytes.subarray(0, GRAPH_ARTIFACT_V2_HEADER.length).toString('utf8'))
      .toBe(GRAPH_ARTIFACT_V2_HEADER)
    expect(currentBytes.length).toBeGreaterThan(1000)
  })

  it('carries an actual normalized snapshot', () => {
    // If it did not, every compatibility control below would be vacuous.
    expect(currentLoad.normalizedAccounting).not.toBeNull()
    expect(currentLoad.normalizedAccounting!.receipt.emitted_candidates).toBeGreaterThan(0)
    expect(currentLoad.graph.numberOfFacts()).toBeGreaterThan(0)
  })
})

describe('S3-5 — current loader, current bytes', () => {
  it('loads and matches the totals the receipt declares', () => {
    const receipt = currentLoad.normalizedAccounting!.receipt
    expect(receipt.facts_retained).toBe(currentLoad.graph.numberOfFacts())
    expect(receipt.occurrences_retained).toBe(currentLoad.graph.numberOfOccurrences())
    expect(receipt.unique_endpoint_pairs).toBe(currentLoad.graph.numberOfEndpointPairs())
  })

  it('attaches a snapshot that matches the receipt', () => {
    const snapshot = currentLoad.graph.normalizedIntegritySnapshot()!
    expect(snapshot.status).toBe(currentLoad.normalizedAccounting!.receipt.status)
    expect(snapshot.emittedCandidates).toBe(currentLoad.normalizedAccounting!.receipt.emitted_candidates)
  })

  it('round-trips every durable record and scope failure', () => {
    const block = currentLoad.normalizedAccounting!
    const snapshot = currentLoad.graph.normalizedIntegritySnapshot()!
    expect(snapshot.unresolvedRecords).toEqual(block.unresolved_records)
    expect(snapshot.rejectedRecords).toEqual(block.rejected_records)
    expect(snapshot.conflictRecords).toEqual(block.conflict_records)
    expect(snapshot.scopeFailures).toEqual(block.scope_failures)
  })

  it('reports truthful normal-mode diagnostics', () => {
    expect(currentLoad.diagnostics).toEqual([])
  })

  it('behaves in strict mode exactly as the declared policy says', () => {
    const status = currentLoad.normalizedAccounting!.receipt.status
    const qualifies = status === 'valid' || status === 'valid_with_warnings'
    if (qualifies) {
      expect(loadGraphArtifact(currentBytes, { mode: 'strict' }).format).toBe('v2')
    } else {
      expect(() => loadGraphArtifact(currentBytes, { mode: 'strict' })).toThrow()
    }
  })
})

describe('S3-5 — current loader, real pre-Stage-3 bytes', () => {
  it('loads them in normal mode', () => {
    expect(loadGraphArtifact(preStage3Bytes).format).toBe('v2')
  })

  it('keeps the storage receipt degraded and storage-only', () => {
    const loaded = loadGraphArtifact(preStage3Bytes)
    expect(loaded.receipt.accounting_scope).toBe('storage_only')
    expect(loaded.receipt.status).toBe('degraded')
  })

  it('leaves the normalized snapshot null', () => {
    const loaded = loadGraphArtifact(preStage3Bytes)
    expect(loaded.normalizedAccounting).toBeNull()
    expect(loaded.graph.normalizedIntegritySnapshot()).toBeNull()
  })

  it('refuses them in strict and qualification mode', () => {
    for (const mode of ['strict', 'qualification'] as const) {
      expect(() => loadGraphArtifact(preStage3Bytes, { mode }))
        .toThrow(/requires normalized candidate accounting/)
    }
  })

  it('leaves facts, occurrences and topology intact', () => {
    const loaded = loadGraphArtifact(preStage3Bytes)
    expect(loaded.graph.numberOfFacts()).toBeGreaterThan(0)
    expect(loaded.graph.numberOfFacts()).toBe(currentLoad.graph.numberOfFacts())
    expect(loaded.graph.numberOfOccurrences()).toBe(currentLoad.graph.numberOfOccurrences())
    expect(loaded.graph.numberOfEndpointPairs()).toBe(currentLoad.graph.numberOfEndpointPairs())
  })

  it('really carries no normalized key', () => {
    expect(preStage3Bytes.toString('utf8')).not.toContain(NORMALIZED_ACCOUNTING_ARTIFACT_KEY)
  })
})

describe('S3-5 — the exact pre-#658 loader reads actual new bytes', () => {
  it('loads them without throwing', () => {
    expect(() => historicalLoader.loadGraphArtifact(currentBytes)).not.toThrow()
  })

  it('keeps its storage-only receipt degraded', () => {
    const loaded = historicalLoader.loadGraphArtifact(currentBytes)
    expect(loaded.format).toBe('v2')
    expect(loaded.receipt.accounting_scope).toBe('storage_only')
    expect(loaded.receipt.status).toBe('degraded')
  })

  it('ignores the additive key rather than carrying it', () => {
    // The old parser copies the storage fields it knows by name, so the key it
    // has never heard of simply does not survive into its receipt.
    const loaded = historicalLoader.loadGraphArtifact(currentBytes)
    expect(Object.keys(loaded.receipt)).not.toContain(NORMALIZED_ACCOUNTING_ARTIFACT_KEY)
  })

  it('recovers the same facts, occurrences and endpoint pairs', () => {
    const loaded = historicalLoader.loadGraphArtifact(currentBytes)
    expect(loaded.graph.numberOfFacts()).toBe(currentLoad.graph.numberOfFacts())
    expect(loaded.graph.numberOfOccurrences()).toBe(currentLoad.graph.numberOfOccurrences())
    expect(loaded.graph.numberOfEndpointPairs()).toBe(currentLoad.graph.numberOfEndpointPairs())
  })

  it('recovers the same endpoint identity projection', () => {
    const loaded = historicalLoader.loadGraphArtifact(currentBytes)
    expect(loaded.receipt.endpoint_identity.fact_pair_counts)
      .toEqual(currentLoad.receipt.endpoint_identity.fact_pair_counts)
    expect(loaded.receipt.endpoint_identity.reason_fact_counts)
      .toEqual(currentLoad.receipt.endpoint_identity.reason_fact_counts)
  })

  it('claims no normalized validity of any kind', () => {
    const loaded = historicalLoader.loadGraphArtifact(currentBytes)
    // Every field it exposes is a storage-boundary field. Nothing in what it
    // returns can be read as "this build accounted for its candidates".
    expect(JSON.stringify(loaded.receipt)).not.toContain('normalized')
    expect(loaded.receipt.status).not.toBe('valid')
  })
})

describe('S3-5 — the compatibility control is not vacuous', () => {
  it('the same loader rejects a bumped receipt storage schema', () => {
    // Proof that the old loader really ran and really inspects these bytes: it
    // refuses a version dimension it is required to refuse, on an artifact
    // identical to the one it just accepted.
    const incompatible = reframe(currentBytes, (payload) => {
      (payload.versions as Record<string, unknown>).receipt_storage_schema = 2
    })
    expect(() => historicalLoader.loadGraphArtifact(incompatible))
      .toThrow(/unsupported version for receipt_storage_schema/)
  })

  it('the same loader rejects a bumped artifact version', () => {
    const incompatible = reframe(currentBytes, (payload) => {
      (payload.versions as Record<string, unknown>).graph_artifact = 3
    })
    expect(() => historicalLoader.loadGraphArtifact(incompatible))
      .toThrow(/unsupported version for graph_artifact/)
  })

  it('the current loader rejects the same controlled incompatibility', () => {
    const incompatible = reframe(currentBytes, (payload) => {
      (payload.versions as Record<string, unknown>).receipt_storage_schema = 2
    })
    expect(() => loadGraphArtifact(incompatible)).toThrow(/unsupported version for receipt_storage_schema/)
  })

  it('accepts the unmutated bytes it rejects the mutated ones from', () => {
    // The pair is what makes the control meaningful: same file, one field
    // changed, opposite outcomes.
    expect(() => historicalLoader.loadGraphArtifact(currentBytes)).not.toThrow()
  })
})

describe('S3-5 — the additive key is what makes the two artifacts differ', () => {
  it('is present in the new bytes and absent from the old', () => {
    expect(currentBytes.toString('utf8')).toContain(NORMALIZED_ACCOUNTING_ARTIFACT_KEY)
    expect(preStage3Bytes.toString('utf8')).not.toContain(NORMALIZED_ACCOUNTING_ARTIFACT_KEY)
  })

  it('is all the old reader sees change, because it sees nothing change', () => {
    const withoutBlock = reframe(currentBytes, (payload) => {
      delete (payload.integrity_receipt as Record<string, unknown>)[NORMALIZED_ACCOUNTING_ARTIFACT_KEY]
    })
    const withKey = historicalLoader.loadGraphArtifact(currentBytes)
    const withoutKey = historicalLoader.loadGraphArtifact(withoutBlock)
    expect(withKey.receipt).toEqual(withoutKey.receipt)
    expect(withKey.graph.numberOfFacts()).toBe(withoutKey.graph.numberOfFacts())
  })

  it('does not change the storage receipt this version writes either', () => {
    const stripped = reframe(currentBytes, (payload) => {
      delete (payload.integrity_receipt as Record<string, unknown>)[NORMALIZED_ACCOUNTING_ARTIFACT_KEY]
    })
    expect(loadGraphArtifact(stripped).receipt).toEqual({
      ...currentLoad.receipt,
      [NORMALIZED_ACCOUNTING_ARTIFACT_KEY]: undefined,
    })
  })
})

describe('S3-5 — bytes stay deterministic across the real publication path', () => {
  it('regenerates identical accounting for the same corpus', () => {
    // `generated_at` moves between runs, so the artifact bytes cannot be
    // compared directly; the accounting they carry must not move at all.
    const second = workspace()
    generateGraph(second, { noHtml: true })
    const other = loadGraphArtifact(readFileSync(join(second, 'out', 'graph.madar')))
    expect(other.normalizedAccounting!.receipt.terminal_counts)
      .toEqual(currentLoad.normalizedAccounting!.receipt.terminal_counts)
    expect(other.normalizedAccounting!.unresolved_records.map((record) => record.id))
      .toEqual(currentLoad.normalizedAccounting!.unresolved_records.map((record) => record.id))
  })

  it('re-serializes the loaded accounting to the same bytes it was loaded from', () => {
    // Scoped to the normalized block on purpose. A whole-payload comparison
    // would also have to reconstruct the provenance and community assignment
    // that generation injected from outside the graph, and a mismatch there
    // would be about those inputs rather than about accounting fidelity.
    const reloaded = loadGraphArtifact(currentBytes)
    const rewritten = serializeGraphArtifactV2({
      graph: reloaded.graph,
      repositoryRevision: reloaded.repositoryRevision,
      generationMode: reloaded.generationMode,
      generatedAt: reloaded.generatedAt,
    })
    const written = JSON.parse(rewritten.toString('utf8').slice(GRAPH_ARTIFACT_V2_HEADER.length)) as Record<string, unknown>
    const original = JSON.parse(currentBytes.toString('utf8').slice(GRAPH_ARTIFACT_V2_HEADER.length)) as Record<string, unknown>
    const block = (payload: Record<string, unknown>): unknown =>
      (payload.integrity_receipt as Record<string, unknown>)[NORMALIZED_ACCOUNTING_ARTIFACT_KEY]
    expect(JSON.stringify(block(written))).toBe(JSON.stringify(block(original)))
    expect(written.integrity_receipt).toEqual(original.integrity_receipt)
    expect(written.facts).toEqual(original.facts)
    expect(written.occurrences).toEqual(original.occurrences)
  })
})
