import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

describe('roadmap documentation', () => {
  it('documents the public roadmap page and links it from the README', () => {
    const roadmap = readFileSync(resolve('docs/roadmap.md'), 'utf8')
    const readme = readFileSync(resolve('README.md'), 'utf8')
    const contributing = readFileSync(resolve('CONTRIBUTING.md'), 'utf8')

    expect(roadmap).toContain('# Public roadmap')
    expect(roadmap).toContain('## Recently shipped')
    expect(roadmap).toContain('## v0.26')
    expect(roadmap).toContain('## v0.27')
    expect(roadmap).toContain('## v0.28')
    expect(roadmap).toContain('## v0.29')
    expect(roadmap).toContain('## v0.30')
    expect(roadmap).toContain('issues/425')
    expect(roadmap).toContain('issues/430')
    expect(roadmap).toContain('issues/432')
    expect(roadmap).toContain('issues/472')
    expect(roadmap).toContain('issues/431')
    expect(roadmap).toContain('issues/429')
    expect(roadmap).toContain('issues/260')
    expect(roadmap).toContain('issues/261')
    expect(roadmap).toContain('issues/262')
    expect(roadmap).toContain('issues/263')
    expect(roadmap).toContain('issues/331')
    expect(roadmap).toContain('issues/332')
    expect(roadmap).not.toContain('graphify-ts')
    expect(roadmap).toContain('help wanted')
    expect(roadmap).toContain('good first issue')
    expect(roadmap).toContain('runtime trust')
    expect(roadmap).toContain('answer quality')
    expect(roadmap).toContain('docs honesty')
    expect(roadmap).toContain('per-repo spread')
    expect(roadmap).toContain('TypeScript and Node.js framework coverage')
    expect(roadmap).toContain('MCP/session efficiency')
    expect(roadmap).toContain('design-partner workflow loops')
    expect(roadmap).toContain('design-partner reports')
    expect(roadmap).toContain('anonymized workflow notes')
    expect(roadmap).toContain('hosted dashboard')
    expect(roadmap).toContain('share-safe artifacts')
    expect(roadmap).toContain('local html report')
    expect(roadmap).toContain('explicit customer demand')
    expect(roadmap).toContain('distribution channels')
    expect(roadmap).toContain('MCP directories')
    expect(roadmap).toContain('proof/onboarding readiness')
    expect(roadmap).toContain('language expansion')
    expect(roadmap).toContain('evidence gates')
    expect(roadmap).toContain('TypeScript/Node proof')
    expect(roadmap).toContain('no broad parity claim')
    expect(roadmap).toContain('flagship multi-repo enterprise workflow')
    expect(roadmap).toContain('synthetic federation receipt')
    expect(roadmap).toContain('frontend/backend/shared')
    expect(readme).toContain('docs/roadmap.md')
    expect(contributing).toContain('docs/roadmap.md')
    expect(contributing).not.toContain('issues/155')
  })
})
