import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { describe, expect, it } from 'vitest'

import { KnowledgeGraph } from '../../src/contracts/graph.js'
import { serializeGraphArtifactV2 } from '../../src/contracts/graph-artifact.js'
import { loadGraph } from '../../src/runtime/serve.js'
import { loadOrBuildSnapshot } from '../../src/infrastructure/time-travel.js'

/**
 * Two facts between one endpoint pair. The v1 mirror cannot represent this --
 * it collapses to a single link -- so it is exactly what a snapshot loses if
 * it keeps only the mirror.
 */
function parallelFactGraph(): KnowledgeGraph {
  const graph = new KnowledgeGraph({ directed: true })
  graph.addNode('a', { label: 'A' })
  graph.addNode('b', { label: 'B' })
  graph.addEdge('a', 'b', { relation: 'calls', confidence: 'EXTRACTED' })
  graph.addEdge('a', 'b', { relation: 'imports', confidence: 'EXTRACTED' })
  return graph
}

/**
 * A workspace holding a canonical artifact beside a live v1, written directly
 * rather than published.
 *
 * #705 removed the publisher that produced this pair, but the shape itself
 * still exists in the world: any workspace generated by a B1 build has it, and
 * time travel must keep reading those correctly. Writing the files here keeps
 * the fixture honest about that being historical input, not current output.
 */
function publishedWorkspace(): { root: string; outputDir: string } {
  const root = mkdtempSync(join(tmpdir(), 'time-travel-canonical-'))
  const outputDir = join(root, 'out')
  mkdirSync(outputDir, { recursive: true })
  writeFileSync(join(outputDir, 'graph.madar'), serializeGraphArtifactV2({
    graph: parallelFactGraph(),
    repositoryRevision: 'rev',
    generationMode: 'full',
    generatedAt: '2026-08-16T00:00:00.000Z',
  }))
  writeFileSync(join(outputDir, 'graph.json'), JSON.stringify({
    schema_version: 1,
    directed: true,
    nodes: [
      { id: 'a', label: 'A', file_type: 'code', source_file: 'a.ts' },
      { id: 'b', label: 'B', file_type: 'code', source_file: 'b.ts' },
    ],
    // v1 can only carry one of the two facts.
    links: [{ source: 'a', target: 'b', relation: 'calls', confidence: 'EXTRACTED' }],
  }))
  writeFileSync(join(outputDir, 'graph.local.json'), `${JSON.stringify({ root_path: root }, null, 2)}\n`)
  return { root, outputDir }
}

describe('a B1-era workspace really is lossy in its v1 artifact', () => {
  it('keeps two parallel facts canonically and one in the v1 artifact', () => {
    const { root, outputDir } = publishedWorkspace()
    try {
      expect(loadGraph(join(outputDir, 'graph.madar')).numberOfFacts()).toBe(2)

      const mirror = JSON.parse(readFileSync(join(outputDir, 'graph.json'), 'utf8')) as { links: unknown[] }

      // This asymmetry is the whole reason a snapshot must carry graph.madar.
      expect(mirror.links).toHaveLength(1)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })
})

describe('a snapshot preserves the canonical artifact', () => {
  /**
   * Drives the real persistSnapshot through loadOrBuildSnapshot. An earlier
   * version of this suite copied the files itself and asserted on its own copy,
   * so it passed while production copied nothing -- a mutation deleting the
   * canonical copy survived it untouched.
   */
  const build = async (): Promise<{ root: string; snapshotDir: string }> => {
    const { root, outputDir } = publishedWorkspace()
    const snapshot = await loadOrBuildSnapshot({ ref: 'HEAD' }, {
      rootDir: root,
      git: {
        resolveRef: () => 'c'.repeat(40),
        createDetachedWorktree: () => undefined,
        removeWorktree: () => undefined,
      },
      generateGraph: () => ({ graphPath: join(outputDir, 'graph.madar'), reportPath: '' }),
      loadGraphExtractorVersion: () => 1,
    })
    return { root, snapshotDir: dirname(snapshot.graphPath) }
  }

  it('round-trips both parallel facts through a real snapshot', async () => {
    const { root, snapshotDir } = await build()
    try {
      // The snapshot holds the canonical artifact and is read directly.
      expect(loadGraph(join(snapshotDir, 'graph.madar')).numberOfFacts()).toBe(2)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('carries the canonical artifact and the machine-local sidecar', async () => {
    const { root, snapshotDir } = await build()
    try {
      expect(existsSync(join(snapshotDir, 'graph.madar'))).toBe(true)
      expect(existsSync(join(snapshotDir, 'graph.local.json'))).toBe(true)
      expect(JSON.parse(readFileSync(join(snapshotDir, 'graph.local.json'), 'utf8')))
        .toEqual({ root_path: root })
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('carries no v1 mirror beside the canonical artifact', async () => {
    const { root, snapshotDir } = await build()
    try {
      // Inverted at the cutover. A snapshot used to keep a v1 mirror so old
      // readers could use it, which is exactly the two-artifact shape #705
      // refuses: nothing proves the pair describes the same run.
      expect(existsSync(join(snapshotDir, 'graph.madar'))).toBe(true)
      expect(existsSync(join(snapshotDir, 'graph.json'))).toBe(false)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  it('records a snapshot format version so pre-cutover snapshots are rebuilt', async () => {
    const { root, snapshotDir } = await build()
    try {
      const metadata = JSON.parse(readFileSync(join(snapshotDir, 'metadata.json'), 'utf8')) as {
        snapshotFormatVersion?: number
      }

      // Load-bearing: a B1-era snapshot holds a canonical artifact beside a
      // live v1 and cannot be upgraded in place, because the two files may
      // describe different runs. The version invalidates it instead.
      expect(metadata.snapshotFormatVersion).toBe(3)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })
})

describe('a retried snapshot does not inherit the previous attempt', () => {
  it('drops a stale sidecar when the new source has none', async () => {
    const { root, outputDir } = publishedWorkspace()
    try {
      const snapshot = await loadOrBuildSnapshot({ ref: 'HEAD' }, {
        rootDir: root,
        git: {
          resolveRef: () => 'd'.repeat(40),
          createDetachedWorktree: () => undefined,
          removeWorktree: () => undefined,
        },
        generateGraph: () => ({ graphPath: join(outputDir, 'graph.madar'), reportPath: '' }),
        loadGraphExtractorVersion: () => 1,
      })
      expect(existsSync(join(dirname(snapshot.graphPath), 'graph.madar'))).toBe(true)

      // Regenerate with no sidecar, as an interrupted publication would leave
      // things. The canonical artifact stays: it is the snapshot graph itself,
      // and a source without one cannot produce a snapshot at all.
      rmSync(join(outputDir, 'graph.local.json'), { force: true })

      const retried = await loadOrBuildSnapshot({ ref: 'HEAD', refresh: true }, {
        rootDir: root,
        git: {
          resolveRef: () => 'd'.repeat(40),
          createDetachedWorktree: () => undefined,
          removeWorktree: () => undefined,
        },
        generateGraph: () => ({ graphPath: join(outputDir, 'graph.madar'), reportPath: '' }),
        loadGraphExtractorVersion: () => 1,
      })

      // Keeping the old sidecar would leave a snapshot claiming a root path
      // the rebuilt graph never had.
      const dir = dirname(retried.graphPath)
      expect(existsSync(join(dir, 'graph.madar'))).toBe(true)
      expect(existsSync(join(dir, 'graph.local.json'))).toBe(false)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })
})
